version: "3"
# docker run -d --name <CONTAINER_NAME> -p 127.0.0.1:6379:6379 redis

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    command: yarn start
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  dashboard:
    build:
      dockerfile: Dockerfile.dev
      context: ./dashboard
    command: yarn start:dev-win
    stdin_open: true
    tty: true
    volumes:
      - ./dashboard/src:/usr/src/app/src

  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/nodemon.json:/usr/src/app/nodemon.json

  # nginx:
  #   volumes:
  #     - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
